# 1. URL de la base de données (localhost car elle est sur ton PC, port 5432 par défaut)
spring.datasource.url=jdbc:postgresql://localhost:5432/gariconnect_db

# 2. Tes identifiants PostgreSQL (ceux configurés à l'installation)
spring.datasource.username=postgres
spring.datasource.password=gariconnect

# 3. Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. Hibernate - Gestion des tables
# 'update' crée les tables automatiquement ou les modifie sans supprimer tes données
spring.jpa.hibernate.ddl-auto=update

# Affiche les requêtes SQL dans la console d'IntelliJ (très utile pour débugger)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spécifie le dialecte pour PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect