# 1. URL de la base de donnees (A remplacer plus tard par l'URL Render de ta BDD)
spring.datasource.url=jdbc:postgresql://localhost:5432/gariconnect_db

# 2. Tes identifiants PostgreSQL
spring.datasource.username=postgres
spring.datasource.password=gariconnect

# 3. Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. Hibernate - Gestion des tables
# 'update' cree les tables automatiquement ou les modifie sans supprimer tes donnees
spring.jpa.hibernate.ddl-auto=update

# Affiche les requetes SQL dans la console (tres utile pour debugger)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Specifie le dialecte pour PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect